### ISSUE TITLE
difference in google docs and json from newest .deb

### ISSUE THREAD

**Issue by unhammer** [giellalt/lang-smj#109]
Split into these issues:

- [ ] https://github.com/divvun/divvun-gramcheck-web/issues/71
- [ ] https://github.com/divvun/divvun-gramcheck-web/issues/98

```sh
$ echo 'Moadda tjijnnujn, girkkojn ja almulasj bájkijn li dákkár teleslivŋŋasa.'| divvun-checker -l smj | jq
```

```json
{
  "errs": [
    [
      "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      0,
      46,
      "msyn-numphrase-sgcom",
      "Dån la tjállám vigev tállabáhkogihpon",
      [
        "Måttijn tjijnnujn, girkkojn ja almulasj bájkijn",
        "Måttijn tjijnnujn, girkkujn ja almulasj bájkijn"
      ],
      "Tállabáhkovihke"
    ],
    [
      "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      0,
      46,
      "msyn-numphrase-sgine",
      "Dån la tjállám vigev tállabáhkogihpon",
      [
        "Moatten tjijnnun, girkkon ja almulasj bájken"
      ],
      "Tállabáhkovihke"
    ],
    [
      "teleslivŋŋasa",
      57,
      70,
      "typo",
      "Báhko \"teleslivŋŋasa\" la vuojnnet boasstot tjáleduvvam.",
      [
        "dieleslivŋŋasa",
        "dileslivŋŋasa",
        "gelaslivŋŋasa",
        "aleslivŋŋasa",
        "oaleslivŋŋasa",
        "bieleslivŋŋasa",
        "mieleslivŋŋasa",
        "valeslivŋŋasa",
        "teltaslivŋŋasa",
        "tejaslivŋŋasa"
      ],
      "Tjállemvihke"
    ]
  ],
  "text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn li dákkár teleslivŋŋasa."
}
```

ie. three unique suggestions for long grammar error.

But google docs gives five unique suggestions:

![Image](https://github.com/user-attachments/assets/7f302035-bf48-4c0d-97fa-c5f526aced5a)

which includes nonsense combinations like "Moatten tjijnnun, girkkojn ja almulasj bájkijn" and "Moatten tjijnnun, girkkon ja almulasj bájkijn".

```sh
$ apt-cache show giella-smj-speller |grep ^V
Version: 0.2.0+g12034~d55f7e51-3~sid1
```
d55f7e51 seems to be from jan 25th

Is the google docs version outdated?

**Comment by unhammer** [comment]
Not sure if it's related, but it's definitely not using the newest errors.xml:

![Image](https://github.com/user-attachments/assets/ab5e4195-aea4-407f-9dec-58604b0c4fc5)

```sh
$ unzip /usr/share/voikko/4/smj.zcheck errors.xml && grep 'error id' errors.xml
Archive:  /usr/share/voikko/4/smj.zcheck
 extracting: errors.xml
```
```xml
  <error id="msyn-dimin-after-unna">
  <error id="style-short-long">
  <error id="msyn-nom-numeral-jagák">
  <error id="syn-to-sentence-init-copula">
  <error id="syn-from-sentence-init-copula">
  <error id="msyn-l-not-la">
    <error id="msyn-la-not-l">
  <error id="msyn-congr-gænna-gejn">
  <error id="lex-oahpastuvvat-oahpasmuvvat">
  <error id="lex-oahpasmuvvat-oahpastuvvat">
  <error id="typo">
  <error id="guillemets">
  <error id="ellipsis">
  <error id="msyn-nom-gen-Po">
  <error id="msyn-pred-attr">
  <error id="msyn-numeral-accattr">
  <error id="msyn-numeral-attr">
  <error id="msyn-numeral-attr-pl-com">
  <error id="msyn-numeral-attr-pl-ine">
    <error id="msyn-numeral-casecongr-com">
  <error id="msyn-numeral-casecongr2">
  <error id="msyn-numeral-casecongr">
  <error id="msyn-numeral-acccasecongr">
  <error id="msyn-numeral-parcasecongr">
  <error id="msyn-numeral-comcasecongr">
  <error id="msyn-numeral-casecongr-guovte-com">
  <error id="msyn-numeral-acccasecongr-akta">
  <error id="msyn-numerals-with-demopron">
  <error id="msyn-numphrase-sgill">
  <error id="msyn-numphrase-sgacc">
  <error id="msyn-numphrase-sggen">
  <error id="msyn-numphrase-sgela">
  <error id="msyn-numphrase-sgcom">
  <error id="msyn-numphrase-sgine">
  <error id="msyn-verb-cong-rel">
  <error id="msyn-verb-cong-rel2">
  <error id="msyn-congr-ma-mij+verb">
  <error id="msyn-congr-mij-ma+verb">
  <error id="msyn-gut-mij">
  <error id="msyn-mij-gut">
  <error id="msyn-pass-active">
  <error id="syn-subj-before-neg">
  <error id="syn-number_congruence-subj-verb">
  <error id="msyn-liehket-congr-condsg2-condpl3">
  <error id="msyn-sme_bastard_neg">
  <error id="msyn-sme_bastard_neg2">
  <error id="real-ActioGen-PrtPl1">
  <error id="real-PrsPl3-PrtSg3">
  <error id="real-PrtSg3-PrsPl3">
  <error id="real-NegSg2-NegSg3">
  <error id="real-NegSg3-NegSg2">
```

**Comment by snomos** [comment]
The version used by GDocs isn’t updated automatically on each build, it must be installed manually on the api server

**Comment by unhammer** [comment]
ok, seems to be https://github.com/divvun/divvun-gramcheck-web/issues/71

**Comment by snomos** [comment]
This is the list in the MS Word extension:

![Image](https://github.com/user-attachments/assets/9212ef31-fc5e-4ccd-aa35-935922d0fbcd)

Looks much cleaner and more correct than the one in GDocs.

**Comment by snomos** [comment]
And this is what it looks like in GDocs for me:

![Image](https://github.com/user-attachments/assets/e25a9060-3f74-49ad-98d6-cfd63dd110c0)

![Image](https://github.com/user-attachments/assets/d4ff660c-44c4-4198-a1e5-792657b76648)

As far as I can tell this is identical to the one in MS Word, and seems correct and up-to-date to me.

**Comment by snomos** [comment]
@unhammer you can test the api server directly, without using the Google Docs or MS Word plugin:

```sh
curl -X POST -H 'Content-Type: application/json' -i 'https://api-giellalt.uit.no/grammar/smj' \
  --data '{"text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn li dákkár teleslivŋŋasa."}' |\
   grep '{' | jq
```

The output I get is the following:

```json
{
  "text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn li dákkár teleslivŋŋasa.",
  "errs": [
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgcom",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Måttijn tjijnnujn, girkkojn ja almulasj bájkijn"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgine",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Moatten tjijnnun, girkkojn ja almulasj bájkijn"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgcom",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Måttijn tjijnnujn, girkkojn ja almulasj bájkijn",
        "Måttijn tjijnnujn, girkkujn ja almulasj bájkijn"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgine",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Moatten tjijnnun, girkkon ja almulasj bájkijn"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgcom",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Måttijn tjijnnujn, girkkojn ja almulasj bájkijn",
        "Måttijn tjijnnujn, girkkujn ja almulasj bájkijn"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgine",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Moatten tjijnnun, girkkon ja almulasj bájken"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "teleslivŋŋasa",
      "start_index": 57,
      "end_index": 70,
      "error_code": "typo",
      "description": "Báhko \"teleslivŋŋasa\" la vuojnnet boasstot tjáleduvvam.",
      "suggestions": [
        "dieleslivŋŋasa",
        "dileslivŋŋasa",
        "aleslivŋŋasa",
        "oaleslivŋŋasa",
        "bieleslivŋŋasa",
        "mieleslivŋŋasa",
        "valeslivŋŋasa",
        "teltaslivŋŋasa",
        "tejaslivŋŋasa",
        "gileslivŋŋasa"
      ],
      "title": "Tjállemvihke"
    }
  ]
}
```

**Comment by unhammer** [comment]
That is certainly odd. I clicked "Extensions→Divvun Grammar Checker→Help→View in store" and it shows

![Image](https://github.com/user-attachments/assets/0373bb6a-4f9d-493a-98e4-0e25519fd4f7)

language selected like

![Image](https://github.com/user-attachments/assets/d5d94cb8-b197-4909-aa48-3d82401b1baa)

**Comment by unhammer** [comment]
(But the output you're getting from the API is outdated compared to newest zcheck.)

**Comment by snomos** [comment]
> Could it be that I've had this extension installed long time ago and it's caching something in my user preferences?

That is possible. You could try to reload the (grammar checker) frame, and see if that helps (right-click within the frame).

> (But the output you're getting from the API is outdated compared to newest zcheck.)

That is very likely. I can upload a new version if you want to test the newest code in production.

**Comment by unhammer** [comment]
libdivvun e1da66bf8655477112091dea6b70f80efc2b0ed7 from October 16th ought to be new enough

**Comment by snomos** [comment]
> haha, yes I did `localStorage.clear()` in the various iframes. So errors.xml is a separate caching issue.

good good, I was afraid there was a major issue in there somewhere 😮

**Comment by snomos** [comment]
I fixed the syntax error, rebuilt it, and handed over a new zcheck file to the api admins. Should be online very soon.

**Comment by snomos** [comment]
… and it is updated on the server 🙂

**Comment by snomos** [comment]
This command:

```sh
curl -X POST -H 'Content-Type: application/json' -i 'https://api-giellalt.uit.no/grammar/smj' \
  --data '{"text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn li dákkár teleslivŋŋasa."}' | grep '{' | jq
```

now returns:

```json
{
  "text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn li dákkár teleslivŋŋasa.",
  "errs": [
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgcom",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Måttijn tjijnnujn, girkkojn ja almulasj bájkijn",
        "Måttijn tjijnnujn, girkkujn ja almulasj bájkijn"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "Moadda tjijnnujn, girkkojn ja almulasj bájkijn",
      "start_index": 0,
      "end_index": 46,
      "error_code": "msyn-numphrase-sgine",
      "description": "Dån la tjállám vigev tállabáhkogihpon",
      "suggestions": [
        "Moatten tjijnnun, girkkon ja almulasj bájken"
      ],
      "title": "Tállabáhkovihke"
    },
    {
      "error_text": "teleslivŋŋasa",
      "start_index": 57,
      "end_index": 70,
      "error_code": "typo",
      "description": "Báhko \"teleslivŋŋasa\" la vuojnnet boasstot tjáleduvvam.",
      "suggestions": [
        "dieleslivŋŋasa",
        "dileslivŋŋasa",
        "gelaslivŋŋasa",
        "aleslivŋŋasa",
        "oaleslivŋŋasa",
        "bieleslivŋŋasa",
        "mieleslivŋŋasa",
        "valeslivŋŋasa",
        "teltaslivŋŋasa",
        "tejaslivŋŋasa"
      ],
      "title": "Tjállemvihke"
    }
  ]
}
```

which is equivalent to what @unhammer gets on the command line.

I consider this bug fixed.

**Comment by unhammer** [comment]
I get the same from the curl command, but google docs is still showing way too many suggestions. 

It seems like I'm also affected by https://github.com/divvun/divvun-gramcheck-web/issues/99
